apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: observability
servers: 1
agents: 2
ports:
  - port: 9090:30090
    nodeFilters:
      - loadbalancer
  - port: 30300:30300
    nodeFilters:
      - loadbalancer
  - port: 3100:3100
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
