version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"

    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: rabbitmq

  order-service:
    build:
      context: .
      dockerfile: OrderService.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      TRANSPORT: rabbitmq
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
    ports:
      - "${ORDER_HTTP_PORT:-8081}:8080"
    container_name: order-service

  notification-service:
    build:
      context: .
      dockerfile: NotificationService.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail","http://localhost:8080/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      ASPNETCORE_URLS: http://+:8080
      TRANSPORT: rabbitmq
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
    ports:
      - "${NOTIFICATION_HTTP_PORT:-8082}:8080"
    container_name: notification-service
