services:
  catalog:
    build: ./CatalogService
    ports:
      - "8080:8080"
  basket:
    build: ./BasketService
    ports:
      - "8081:8080"
  order:
    build: ./OrderService
    ports:
      - "8082:8080"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  gateway:
    build: ./ApiGateway
    ports:
      - "9000:8080"
    depends_on:
      - catalog
      - basket
      - order
